export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export const GET_CURRENT_USER_CART_REQUEST = "GET_CURRENT_USER_CART_REQUEST";
export const GET_CURRENT_USER_CART = "GET_CURRENT_USER_CART";
export const GET_CURRENT_USER_CART_FAIL = "GET_CURRENT_USER_CART_FAIL";

export const UPDATE_ITEM_CART = "UPDATE_ITEM_CART";

export const CHECKOUT_REQUEST = "CHECKOUT_REQUEST"
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS"
export const CHECKOUT_FAIL = "CHECKOUT_FAIL"

export const PROCESS_ORDER_REQUEST = "PROCESS_ORDER_REQUEST"
export const PROCESS_ORDER_SUCCESS = "PROCESS_ORDER_SUCCESS"
export const PROCESS_ORDER_FAIL = "PROCESS_ORDER_FAIL"
