
export const DELETE_SUPPLIER_REQUEST = "DELETE_SUPPLIER_REQUEST";
export const DELETE_SUPPLIER_SUCCESS = "DELETE_SUPPLIER_SUCCESS";
export const DELETE_SUPPLIER_RESET = "DELETE_SUPPLIER_RESET";
export const DELETE_SUPPLIER_FAIL = "DELETE_SUPPLIER_FAIL";

export const UPDATE_SUPPLIER_REQUEST = "UPDATE_SUPPLIER_REQUEST";
export const UPDATE_SUPPLIER_SUCCESS = "UPDATE_SUPPLIER_SUCCESS";
export const UPDATE_SUPPLIER_RESET = "UPDATE_SUPPLIER_RESET";
export const UPDATE_SUPPLIER_FAIL = "UPDATE_SUPPLIER_FAIL";

export const SUPPLIER_DETAILS_REQUEST = "SUPPLIER_DETAILS_REQUEST";
export const SUPPLIER_DETAILS_SUCCESS = "SUPPLIER_DETAILS_SUCCESS";
export const SUPPLIER_DETAILS_FAIL = "SUPPLIER_DETAILS_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
